# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.56.302"
  config.vm.hostname = "k3s-worker2"
  config.vbguest.auto_update = false

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.provider "virtualbox" do |vb|
     vb.name = "k3s-worker2"
     vb.cpus = 2
     vb.memory = "2048"
  end
   
  config.vm.provision "shell", inline: <<-SHELL
  # Đặt pass 123 có tài khoản root và cho phép SSH

  echo "install ssh root/123"
  echo "123" | passwd --stdin root
  sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
  systemctl reload sshd

  sudo yum update -y 

  # fix loi khong tim thay kernel
  sudo yum install -y kernel-devel-$(uname -r)

SHELL
end