# -*- mode: ruby -*-
# vi: set ft=ruby :

# Tạo máy ảo từ box centos/7, gán địa chỉ IP, đặt hostname, gán 2GB bộ nhớ, 2 cpus  
Vagrant.configure("2") do |config|
    config.vm.box = "centos/7"
    config.vm.network "private_network", ip: "192.168.56.30"
    config.vm.hostname = "k3s-master"
    config.vbguest.auto_update = false

    config.vm.provider "virtualbox" do |vb|
       vb.name = "k3s-master"
       vb.cpus = 2
       vb.memory = "2048"
    end

     # Chạy file install-docker-kube.sh sau khi nạp Box
     config.vm.provision "shell", path: "./../base-setup.sh"

    # Chạy các lệnh shell
    config.vm.provision "shell", inline: <<-SHELL
      # Đặt pass 123 có tài khoản root và cho phép SSH

	    echo "install ssh root/123"
      echo "123" | passwd --stdin root
      sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      systemctl reload sshd

      sudo yum update -y 

      # fix loi khong tim thay kernel
      sudo yum install -y kernel-devel-$(uname -r)
  
    SHELL
  end